default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rwork01_development

test:
  <<: *default
  database: rwork01_test

production:
  <<: *default
  database: rwork01_production
  username: rwork01
  password: <%= ENV['RWORK01_DATABASE_PASSWORD'] %>
